# Generated by Django 3.2.23 on 2023-12-24 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arraydbs',
            old_name='sorted_array',
            new_name='array',
        ),
    ]
